### ISSUE TITLE
Methods PATCH & PUT don't work with field type file

### ISSUE THREAD

**Issue by debian-sh** [Sealious/sealious#244] opened 2015-11-30 00:38 UTC
I've discovered that PATCH & PUT methods don't work with field type file. When I sent PATCH or PUT to existing resource with new file, I received this error:

* Response
```js
{
    "data": {
        "file": "Wrong file data format. Should be <Buffer>, but received undefined"
    },
    "is_error": true,
    "type": "validation",
    "status_message": "There are problems with some of the provided values."
}
```
* Stack
```js
01:26:08.879 - error: 	PATCH /api/v1/person/r5jk9ddk2g
			from: 127.0.0.1, mime: multipart/form-data
			result: failed - There are problems with some of the provided values.
Error: There are problems with some of the provided values.
    at new SealiousErrors.Error (/home/arkadiusz/Projects/hello-world/node_modules/sealious/lib/response/error.js:6:12)
    at new SealiousErrors.ValidationError (/home/arkadiusz/Projects/hello-world/node_modules/sealious/lib/response/error.js:21:12)
    at /home/arkadiusz/Projects/hello-world/node_modules/sealious/lib/chip-types/resource-type.js:175:28
    at bound (domain.js:250:14)
    at runBound (domain.js:263:12)
    at tryCatcher (/home/arkadiusz/Projects/hello-world/node_modules/sealious/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/arkadiusz/Projects/hello-world/node_modules/sealious/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/arkadiusz/Projects/hello-world/node_modules/sealious/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/arkadiusz/Projects/hello-world/node_modules/sealious/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/arkadiusz/Projects/hello-world/node_modules/sealious/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/arkadiusz/Projects/hello-world/node_modules/sealious/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/arkadiusz/Projects/hello-world/node_modules/sealious/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```
* Client request
```js
------WebKitFormBoundary1l2BQEaJzZ5OWM3W
Content-Disposition: form-data; name="file"; filename="1_283.png"
Content-Type: image/png


------WebKitFormBoundary1l2BQEaJzZ5OWM3W--
```

* My structure ResourceType
```js
new Sealious.ChipTypes.ResourceType({
	name: "person",
	fields: [{name: "file", type: "file"}]
});
```

**Comment by groovy354** [comment] 2015-12-01 09:01
For some reason www-server does not wrap file buffers in `Sealious.File`. Probably has to do with the fact that `/resource_type/id` does not check resource_type's `handles_large_data` flag

**Comment by debian-sh** [comment] 2015-12-01 20:21
Ok

**Comment by groovy354** [comment] 2015-12-07 17:44
Hi, sorry for the delay. The issue is fixed in `channel-rest`. Please update your application's `channel-rest` to v0.1.4. 
If the issue is resolved for you, please close this issue.

**Comment by debian-sh** [comment] 2015-12-07 18:37
Thanks for feedback, I will check this tomorrow :)

**Closed** 2015-12-08 12:14 UTC
